FROM node:lts-alpine

ENV NEXT_PUBLIC_LANDINGPAGE_URL=NEXT_PUBLIC_LANDINGPAGE_URL
ENV NEXT_PUBLIC_APP_URL=NEXT_PUBLIC_APP_URL
ENV NEXT_PUBLIC_API_URL=NEXT_PUBLIC_API_URL
ENV NEXT_PUBLIC_PONDER_URL=NEXT_PUBLIC_PONDER_URL
ENV NEXT_PUBLIC_WAGMI_ID=NEXT_PUBLIC_WAGMI_ID
ENV NEXT_PUBLIC_ALCHEMY_API_KEY=NEXT_PUBLIC_ALCHEMY_API_KEY
ENV NEXT_PUBLIC_CHAIN_NAME=NEXT_PUBLIC_CHAIN_NAME
ENV NEXT_PUBLIC_RPC_URL_MAINNET=NEXT_PUBLIC_RPC_URL_MAINNET
ENV NEXT_PUBLIC_RPC_URL_POLYGON=NEXT_PUBLIC_RPC_URL_POLYGON

COPY entrypoint.sh /usr/bin/

RUN \
chmod 755 /usr/bin/entrypoint.sh \
&& mkdir /app \
&& chown -R node:node /app

WORKDIR /app
USER node

COPY --chown=node . .
RUN \
yarn install --frozen-lockfile \
&& yarn build

ENTRYPOINT ["entrypoint.sh"]
CMD ["yarn", "start"]
