import React, { useEffect, useState } from "react";
import Head from "next/head";
import EquityFPSDetailsCard from "@components/PageEquity/EquityFPSDetailsCard";
import EquityInteractionCard from "@components/PageEquity/EquityInteractionCard";
import AppTitle from "@components/AppTitle";
import { useAccount } from "wagmi";
import { FPSBalanceHistory } from "../hooks/FPSBalanceHistory";
import { FPSEarningsHistory } from "../hooks/FPSEarningsHistory";
import ReportsFPSYearlyTable from "@components/PageReports/ReportsFPSYearlyTable";
import { zeroAddress } from "viem";
import AppLink from "@components/AppLink";
import AppHeroSteps from "@components/AppHeroSteps";
import { ContractUrl } from "@utils";
import { ADDRESS } from "@frankencoin/zchf";
import { mainnet } from "viem/chains";

export default function Equity() {
	const { address } = useAccount();
	const [fpsHistory, setFpsHistory] = useState<FPSBalanceHistory[]>([]);
	const [fpsEarnings, setFpsEarnings] = useState<FPSEarningsHistory[]>([]);

	useEffect(() => {
		if (address == undefined) {
			setFpsHistory([]);
			setFpsEarnings([]);
			return;
		}

		const fetcher = async () => {
			try {
				const responseBalance = await FPSBalanceHistory(address);
				setFpsHistory(responseBalance.reverse());

				const responseEarnings = await FPSEarningsHistory(address);
				setFpsEarnings(responseEarnings.reverse());
			} catch (error) {
				console.log(error);
			}
		};

		fetcher();
	}, [address]);

	return (
		<>
			<Head>
				<title>Frankencoin - Invest</title>
			</Head>

			<AppTitle title={`Invest`}>
				<div className="text-text-secondary">
					Invest in or redeem your{" "}
					<AppLink className="" label="Frankencoin Pool Shares" href={ContractUrl(ADDRESS[mainnet.id].equity)} external={true} />{" "}
					(FPS) — the governance token of the Frankencoin Ecosystem.
				</div>
			</AppTitle>

			<AppHeroSteps
				steps={[
					{
						icon: 1,
						title: "Buy FPS",
						description: "Invest ZCHF to receive Frankencoin Pool Shares and become part of the ecosystem.",
					},
					{
						icon: 2,
						title: "Earn from protocol revenue",
						description: "FPS holders capture fees generated by the protocol.",
					},
					{
						icon: 3,
						title: "Govern the protocol",
						description: "Use your FPS to vote on protocol decisions and shape the ecosystem.",
					},
				]}
			/>

			<div className="md:mt-8">
				<section className="grid grid-cols-1 md:grid-cols-2 gap-4 mx-auto">
					<EquityInteractionCard />
					<EquityFPSDetailsCard />
				</section>
			</div>

			<AppTitle title="Attributable Income">
				<div className="text-text-secondary">
					Historic system income <AppLink className="text-left" label={"attributable to the current address"} href={`/report`} />.
				</div>
			</AppTitle>
			<ReportsFPSYearlyTable address={address || zeroAddress} fpsHistory={fpsHistory} fpsEarnings={fpsEarnings} />
		</>
	);
}
